### ISSUE TITLE
Crear activity para elegir cuenta de transacciones favoritas

### ISSUE THREAD

**Issue by ericpennachini** [mauricioarielramirez/ProyectoProgramacionMovil#16]
Esta activity va a cumplir la función de elegir la cuenta a la que una transacción favorita está asociada, en el caso de las transacciones que estén asociada a más de una cuenta.

**Comment by mauricioarielramirez** [comment]
Se utilizó ElegirCuentaActivity para esta funcionalidad. Se modificó la información contenida en el bundle de recepción y emisión hacia la TransaccionActivity.
