### ISSUE TITLE
Error al modificar cuenta

### ISSUE THREAD

**Issue by mauricioarielramirez** [mauricioarielramirez/ProyectoProgramacionMovil#22]
Cuando se modifica una cuenta (denominacionCuenta), se pierde la relación con las transacciones que tenía originalmente asociada. Se sugiere revisar el comportamiento ON UPDATE CASCADE para evaluar si se hace la actualización correspondiente sobre la tabla db_cuenta_transaccion.

**Comment by ericpennachini** [comment]
Se corrigió agregando la siguiente el siguiente código: 

`@Override`
`public void onOpen(SQLiteDatabase db) {`
`        super.onOpen(db);`
`        if (!db.isReadOnly()) {`
`            // Enable foreign key constraints`
`            db.execSQL("PRAGMA foreign_keys=ON;");`
`        }`
` }`

Se colocó en la clase Dao, sobreescribiendo un método de la clase `SQLiteOpenHelper`
