### ISSUE TITLE
Manejo de consultas sobre las cuentas

### ISSUE THREAD

**Issue by ericpennachini** [mauricioarielramirez/ProyectoProgramacionMovil#23]
Realizar la lógica necesaria para el manejo de las consultas sobre las cuentas, de manera informativa. Es decir, poder ver todas las cuentas, sus transacciones y movimientos realizados.

**Comment by mauricioarielramirez** [comment]
Propuesta para la consulta, viniendo previamente de seleccionar una cuenta:
![image](https://user-images.githubusercontent.com/11452432/36355451-1a46f2f0-14c2-11e8-8c99-e1065f259af7.png)
Por rango de fechas:
![image](https://user-images.githubusercontent.com/11452432/36355457-324d147e-14c2-11e8-9caf-2555972e0aae.png)
Comparando periodos
![image](https://user-images.githubusercontent.com/11452432/36355460-441e1176-14c2-11e8-9b79-71201c270efa.png)

**Comment by mauricioarielramirez** [comment]
@ericpennachini Se adjunta la base de datos de prueba, la consulta debería realizarse desde el 1/02/2018 al 28/02/2018 y desde el 01/03/2018 al 31/03/2018 (se cuenta con datos en esos periodos de fechas)

[db_proyecto.zip](https://github.com/mauricioarielramirez/ProyectoProgramacionMovil/files/1867358/db_proyecto.zip)

**Comment by mauricioarielramirez** [comment]
**_Prestar atención al issue #26_**

**Comment by mauricioarielramirez** [comment]
Se cierra porque no se realizarán cambios significativos en la búsqueda de movimientos.
