### ISSUE TITLE
Fechas ConfigurarConsultaActivity

### ISSUE THREAD

**Issue by mauricioarielramirez** [mauricioarielramirez/ProyectoProgramacionMovil#27]
Se debe realizar las validaciones para que las fechas de los periodo desde y periodo hasta no se superpongan. 

![image](https://user-images.githubusercontent.com/11452432/39667181-a2b3ac28-5086-11e8-87be-6fddbbd2712b.png)

**Comment by ericpennachini** [comment]
La solución propuesta para el caso del período normal es:

- Establecer ambas fechas en el día actual. Si se elige primero el botón de _Fecha desde_, establecer la _Fecha hasta_ con el mismo valor que la _Fecha desde_. Si se quiere elegir una _Fecha hasta_ menor a _Fecha desde_ **se deberá rechazar el cambio y mostrar una advertencia en un toast.**

- De forma análoga, se realiza el mismo procedimiento si se elige _Fecha hasta_ primero.


La solución propuesta para el caso de la comparación de períodos es:

- Habilitar los campos en el orden _desde1_, _hasta1_, _desde2_, _hasta2_. La primera vez el campo _desde1_ estará habiltado por defecto.

- Se van editando los campos secuencialmente y se va validando que la fecha ingresada sea mayor o igual al campo inmediato anterior (por ejemplo, si se está editando el campo _desde2_ se validará que se ingrese una fecha mayor o igual a _hasta1_).

- Para este caso se va a habilitar un botón _Restablecer_, el cual servirá para restablecer los campos (es decir, dejar habilitado solo _desde1_ con la fecha actual).

**Comment by ericpennachini** [comment]
Para el caso de la consulta de períodos, se dejan habilitados _todos_ los campos, y se valida inicio y fin dentro de cada período individualmente. Luego, al hacer clic en "Consultar" se valida que el fin del periodo 1 no sea mayor que el inicio del periodo 2.
